version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"   # default edge port for all services (including S3)
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
    
      - "/var/run/docker.sock:/var/run/docker.sock"
